name: Maven Build and Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual build (e.g., testing)"
        required: true
        default: "Manual build test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (Maven requires JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install  # Compiles, runs tests, and packages the JAR

      # Optional: Run additional tests or custom goals
      - name: Run Integration Tests
        run: mvn verify -Pintegration-tests  # Example for profile-based tests
